baseurl = "/"
languageCode = "en-us"
title = "Runhang's website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "https-www-runhangshu-com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "ABOUT"
    url = "/about.html"
    weight = 3
[[menu.main]]
    name = "VITAE"
    url = "https://uflorida-my.sharepoint.com/:w:/r/personal/r_shu_ufl_edu/_layouts/15/Doc.aspx?sourcedoc=%7B7497ED2C-41FA-4762-B96E-9B91EE81A1D1%7D&file=CV_12162020.docx&action=default&mobileredirect=true"
    weight = 4
[[menu.main]]
    name = "TWITTER"
    url = "https://twitter.com/Runhang1"
    weight = 2
[[menu.main]]
    name = "思想报告"
    url = "/post2/"
    weight = 5
    [[menu.main]]
    name = "BIOINFORMATICS"
    url = "/r/"
    weight = 1

[params]
    description = "A boring blog talk about everything"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    disqusURL = "https://www.runhangshu.com"
    # path to the favicon, under "static"
    favicon = "favicon2.ico"

    [params.logo]
    url = "favicon2.ico"
    width = 150
    height = 300
    alt = "Logo"
